version: "3"

services:
  reverse-proxy:
    image: traefik:v2.5
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: book_shop
      MYSQL_DATABASE: book_shop
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping"]

  myerl:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      MYERL_DB_PASSWORD: book_shop
    labels:
      - "traefik.http.routers.myerl.rule=Host(`myerl.docker.localhost`)"
    depends_on:
      db:
        condition: service_healthy
